### ISSUE TITLE
load state from url

### ISSUE THREAD

**Issue by imneckro** [EmulatorJS/EmulatorJS#12]
Hello everyone.
This is a question and not an issue.
IS there a way to customize js code in which users can save their states at server side and load them from there?
Any ideas anyone?

**Comment by ethanaobrien** [comment]
No, there is no way to be able to to this. Although this would be cool. I dont know if this is possible though.

**Comment by ethanaobrien** [comment]
I will work on this soon

**Comment by ethanaobrien** [comment]
@imneckro I added support for this, sometimes there is a short delay when starting because it has to fetch the state.

when defining the pathtodata and gameurl also add the line

```
EJS_loadStateURL = 'gameSaveState.state';
```

If you would like to load from a url in the middle of a game (like you add buttons with different save states) just re-define the `EJS_loadStateURL` variable and then call the function `EJS_loadStateFromURL` with no arguments.

If there are any problems, please let me know

**Comment by imneckro** [comment]
@ethanaobrien Im tyring to use EJS_loadStateURL = 'gameSaveState.state'; but no save loads

**Comment by raulbojalil** [comment]
If you are trying to load your save in the middle of the game you can use the EJS_onLoadState callback, fetch your save there and then use the EJS_loadState(byte array) function to load your state. You can see an example here: https://github.com/raulbojalil/flemu/blob/master/backend/public/emulator/index.html#L39

**Comment by imneckro** [comment]
Im not trying to load in the middle but from the beginning using EJS_loadStateURL = 'gameSaveState.state';

**Comment by raulbojalil** [comment]
Is your file actually called "gameSaveState.state" and it's placed at the root of your server? Maybe you are getting a 404 on that file?. Tbh I haven't used that property before.

**Comment by imneckro** [comment]
its named accordingly and points to the right path
