### ISSUE TITLE
Library Selection

### ISSUE THREAD

**Issue by moiez0** [emulatorjs/emulatorjs#206]
A feature where you can allow the user to select any rom in a folder would be cool
Like a drop down in which the user can select a rom

e.g
EJS_gamesdir = '';

**Comment by ethanaobrien** [comment]
This isnt really possible. You cant read the contents of a directory from the client. You'd have to define each file and each core

**Comment by Ramaerel** [comment]
I could have an attempt at building this on as a separate addition for you if you want, although it wouldn't be a direct part of this (unless Ethan wants it)
Be a good chance to continue learning more 😊

**Comment by ethanaobrien** [comment]
Yeah sure. Go ahead. Have fun. Ill accept a pull request (maybe after cleaning some things)

**Comment by moiez0** [comment]
@Ramaerel Sounds good to me! Thanks

**Comment by Ramaerel** [comment]
I have spent the large majority of the day trying to figure out how to use github, I've opted to create my own repo for this because quite honestly, its the only thing I could find. It isn't overly nice looking, but it reads all your roms from the /roms/ folder and creates a simple form to select them from. I'm definitely gonna spend some time prettying it up, and maybe even convert it to javascript so it can run fully clientside. Right now it requires to be hosted or at least some sort of php program like XAMPP. If you want to take it and do something with it, Ethan, it's all yours. I'll keep updating it because it's given me ideas though.

It can be found here: https://github.com/Ramaerel/emulatorjs-GameLibrary

**Comment by ethanaobrien** [comment]
hmm didnt think about using php. one suggestion. Can you put all the contents into an array so that you can also manually enter the file contents (as php is not supported by most simple web servers)

**Comment by Ramaerel** [comment]
I'll take a look and try some other things later, the next 3 days are pretty full for me but after that I can try

**Comment by ethanaobrien** [comment]
@mgamingpro Is there anything else you need or can I close this?
