### ISSUE TITLE
Removing the controller and interface

### ISSUE THREAD

**Issue by cpgb85** [emulatorjs/emulatorjs#253]
Everything the emulator provides, I basically want to remove but there is no obvious way of doing this.  I want to program my own on screen controls because the current ones are not up to snuff.

**Comment by ethanaobrien** [comment]
This would be pretty difficult. Can you tell me specifically the things you might want to change so I can point you in the right direction?

Basically, all of the css is defined in emu-css.css, and in emulator.js you can search for ejs-- and it should pop up with the translations between the class names and the emulator uses. You could change these class names if you want or you could edit the classes themselves.

**Comment by cpgb85** [comment]
Sure.  I need to be able to scale controls, move the controls, and lastly the a + b buttons don't register button presses while dragging from one button to another.  I have to physically pick my finger up to press another button.

Would be a bit nice to strip away all the other things, and just have the NES emulator by itself, or any emulator without the shaders, controllers, and all the other settings.

**Comment by ethanaobrien** [comment]
Search the emulator.js file for virtualGamepad. One of the results will contain the code that has all the button settings and stuff like that

Also, are you saying that when dragging off the button the up event isn’t being sent or that the down event isn’t being sent until you lift up your finger?

Somewhere around where I fetch the v.json file, when the emulator is set to the beta version (coreVer 2) then it will hide some of the buttons. You could pretty easily hide the buttons you don’t want that way. The format is somewhat simple.

For clearing the options, there’s a json variable in the emu-main.js file. It has the default options (which are shader and virtualGamepad) and then there’s another function (I’m pretty sure it’s also in the emu-main.js file) that all it does it set the menu options. The menu options are cleared by default on beta (coreVer 2) so that might help in looking for that (or you could just hide the settings button altogether.

In the loader.js file, you could auto set the core option to nes if you wanted it to be an nes only kinda thing.

Sorry that I haven’t been able to send actual links to the code. Can’t get on the actual website right now.

**Comment by cpgb85** [comment]
You have been an enormous amount of help! This is probably the best JavaScript emulator platform I have found.  I love that it supports mapper 30 for NES maker games. Great job!

**Comment by ethanaobrien** [comment]
No problem! And thank you! I love maintaining this project

If you have any other questions you can always ask

If you have no other questions could you please close the issue?

Thanks!
