### ISSUE TITLE
Start Screen Recording

### ISSUE THREAD

**Issue by ildomandatore** [emulatorjs/emulatorjs#270]
I tried Start Screen Recording, but there is no audio. A message says it must be enabled by the system. I hope there is a solution to fix this, as it becomes problematic if all players have no audio while recording.

**Comment by ethanaobrien** [comment]
This can’t be fixed. There is no easy way to record the audio. The only thing I could do was request the system audio

**Comment by ildomandatore** [comment]
Multimedia format designed to provide a royalty-free, high-quality open video compression format for use with HTML5 video. WebM supports the video codec VP8 and VP9.

https://caniuse.com/?search=webm

**Comment by Ramaerel** [comment]
I think it's less about the legality and more what he can do in the program itself

**Comment by ildomandatore** [comment]
The text written by me previously was automatically placed by the link I shared. I wanted the author to look at the page and the links within it. Maybe he find interesting information.

**Comment by ethanaobrien** [comment]
I’ve already done all the searching I can do. It is simply not possible to create the type of stream we want from an audio context (and we don’t even always have access to the audio context).

Changing the format has nothing to do with the fact that we don’t have and can’t get the original audio stream. (It’s already set to webm by default anyway (I think))

The problem is that this isn’t supported by the browsers. There’s no way to achieve what we want. The capture device audio was the only way I could get the audio

**Comment by allancoding** [comment]
This is planed to be fixed on the newer beta retroarch cores. Recording audio context and canvas frame inside of emscripten as retroarch already has this function.

**Comment by ildomandatore** [comment]
Ok. I'll wait.

**Comment by allancoding** [comment]
Based on our findings, we cannot verify that you got a copy of emulatorjs from its official source. The cause of this is because of undocumented changes (meaning, there is no documentation on your site stating changes, which is required by license) or changes that have removed a link to source of the software. Stating the changes and linking to the original source is REQUIRED by license and we will refuse to service those who do not follow the license whether it be a requested feature, a possible bug, or a need for information. We have the right by law to refuse to service you. To dismiss this notice and be able to receive help, then add the stated changes to your website, and make sure a link to this page (or the information on the page itself) is clearly visible, and that there is a clear link to the source of the original GitHub project. If you get this message and make the required changes and break the license in this way again, then you will be prevented from opening any issues in the emulatorjs repository. No help will be given to make these changes (you managed to make the changes that break the license, you can fix it). We apologize for any inconvenience.
