### ISSUE TITLE
Advertising for games hosted on other sites.

### ISSUE THREAD

**Issue by ildomandatore** [emulatorjs/emulatorjs#283]
How do I advertise for games hosted on other sites but not on my website?

**Comment by Ramaerel** [comment]
You would need to create a separate Web page with the ad you want on it (you'll need to use PHP and/or JS to have different ones each time) and then link it in the EJS_Ads = "ad url"; near where you load the roms etc. That EJS stuff could be wrong, it's off the top of my head.

Keep in mind that approach means you won't get paid for it. Alternatively, you can reach out to the site owners directly and they might help you. I don't think there's any outright ad networks for games only

**Comment by ethanaobrien** [comment]
That’s a JavaScript thing. Use some logic to see what domain you’re on and only set `EJS_AdUrl` when it isn’t your site.

i recommend google ads (search it)

please be aware, when redistributing the code (allowing others to use on their site), you MUST (according to the license) make sure the end user knows the changes — that you added ads. You must also point them to the original license. If the license is not followed I will charge back

this isn’t an issue. I’m closing this

**Comment by ildomandatore** [comment]
Sorry, but I don't understand. I am little more than a beginner.

I'm not looking for advertising on video games, but understanding how to place advertising only in games outside my site.

The advertising plugin for wordpress I search for it by myself, but I have to understand how to insert the advertising and what code I should deliver to who will publish the emulated games.

**Comment by ethanaobrien** [comment]
That’s exactly the information I provided

**Comment by ildomandatore** [comment]
I asked to explain in simple words, because I did not understand. :)

**Comment by Ramaerel** [comment]
# 
I'm not sure how WordPress plugins work but basically. The easiest way to do it is to the the code that a ad server like Google Ads will give you and paste it into a separate HTML file, calls ads.html for example. 

After that, just set 
EJS_AdUrl = "./ads.html";
In this example.

**Comment by ildomandatore** [comment]
Got it, I need to copy the game's html code and add that suggested part. Thank you.

**Comment by allancoding** [comment]
Based on our findings, we cannot verify that you got a copy of emulatorjs from its official source. The cause of this is because of undocumented changes (meaning, there is no documentation on your site stating changes, which is required by license) or changes that have removed a link to source of the software. Stating the changes and linking to the original source is REQUIRED by license and we will refuse to service those who do not follow the license whether it be a requested feature, a possible bug, or a need for information. We have the right by law to refuse to service you. To dismiss this notice and be able to receive help, then add the stated changes to your website, and make sure a link to this page (or the information on the page itself) is clearly visible, and that there is a clear link to the source of the original GitHub project. If you get this message and make the required changes and break the license in this way again, then you will be prevented from opening any issues in the emulatorjs repository. No help will be given to make these changes (you managed to make the changes that break the license, you can fix it). We apologize for any inconvenience.
