### ISSUE TITLE
Enter iframe code

### ISSUE THREAD

**Issue by ildomandatore** [emulatorjs/emulatorjs#291]
I should enter the game's iframe code, but I can't. I don't know which game url I should enter. I currently have the url of the game in Zip, but that would make users download the file.

**Comment by allancoding** [comment]
The url of the game can be a `zip` / `rar` / `7z` when setting the:
```
EJS_gameUrl = '';
```

**Comment by ildomandatore** [comment]
I had thought the same thing, but the file is .zip and so it makes you download the file. This is not what I want.

**Comment by allancoding** [comment]
Can you share you html code so we can check your code?

**Comment by ildomandatore** [comment]
```
<div style="width:640px;height:335px;max-width:100%;margin:auto;">
        <div id="game"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#game';
    EJS_core = 'segaMD';
    // URL to Game rom    
    EJS_gameUrl = 'https://oldfreegame.com/wp-content/uploads/2022/07/mickey-mouse-castle-of-illusion-usa.zip';   
    /*
     *  Path to the WASM / JS files
     *  HAS TO BE in the same directory.
     */   
    EJS_pathtodata = 'https://oldfreegame.com/emulatorjs-main/data/';    
</script>
<script src="https://oldfreegame.com/emulatorjs-main/data/loader.js"></script>
```

**Comment by allancoding** [comment]
That should work it does not make the user download the zip it will never to that unless the user goes the the zip location the emulator js code reads the zip and extract it in the browser.
I tested this url and it worked fine.
https://oldfreegame.com/castle-of-illusion-starring-mickey-mouse-mega-dtive/

**Comment by ildomandatore** [comment]
I had tried this solution before coming here. But using the Tryit website, the iframe loads the website. I am perplexed. Should I use another program?

https://postimg.cc/WFMzmTy3

**Comment by ethanaobrien** [comment]
That’s because of the websites security policy. It cannot load external scripts

**Comment by ethanaobrien** [comment]
Based on our findings, we cannot verify that you got a copy of emulatorjs from its official source. The cause of this is because of undocumented changes (meaning, there is no documentation on your site stating changes, which is required by license) or changes that have removed a link to source of the software. Stating the changes and linking to the original source is REQUIRED by license and we will refuse to service those who do not follow the license whether it be a requested feature, a possible bug, or a need for information. We have the right by law to refuse to service you. To dismiss this notice and be able to receive help, then add the stated changes to your website, and make sure a link to this page (or the information on the page itself) is clearly visible, and that there is a clear link to the source of the original GitHub project. If you get this message and make the required changes and break the license in this way again, then you will be prevented from opening any issues in the emulatorjs repository. No help will be given to make these changes (you managed to make the changes that break the license, you can fix it). We apologize for any inconvenience.
