### ISSUE TITLE
Direct link from external source

### ISSUE THREAD

**Issue by megamandev** [emulatorjs/emulatorjs#302]
using external ulr link in the path of the rom. the game does not work. but when I put the path to the same place where the emulator is, it works normal

example

my link url external: abccloud.net

EJS_paths = {
    'fileName' : 'https://abccloud.net/n64/mario64.zip',  > rom with external link not work
    'fileName' : 'https://xyzcloud.net/n64/mario64.zip', > rom with same domain link work 
    'emulator.js' : 'https://xyzcloud.net/emulator.js',
    'n64-asmjs.data' : 'https://xyzcloud.net/data/n64-old-asmjs.data'
};

can implement for this emulator to work the rom. using external link in the path of the rom

cheers!

**Comment by ethanaobrien** [comment]
This isnt a bug on my side. The emulator always has supported roms from other sites (I'm going to close this but I'm still going to try and help you)

the filename cant be defined in EJS_paths. You must use the EJS_gameUrl setting. Also, this could be because of CORS. You can learn more about it [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)
