### ISSUE TITLE
The new SNES wasm is missing some setting (like shader)

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#312]
Hi,

First of all, I would like to say thank you - I really appreciate your hard work... 

I've updated the cores wasm files (that you've released today), and i've noticed that snes games is missing some of the settings options that appreared on the previous version (for example: shader, overclock, ect..).

Is it a bug? or did you remove this options specificlly on the snes emulator?

BTW, I've noticed that the new version of emulatorjs support more games like goldenaxe death adder (while this version doesn't support it yet) - will you update the wasm?

**Comment by ethanaobrien** [comment]
Hello, 

no it’s not a bug, I’ve been working on making the new cores compiled straight from retroarch (so I can say 100% what I am putting into my project) and I haven’t done that part yet, it’s just not supported yet.

shader is supported, that part is a bug.

I can no longer update from the emulatorjs website, see #223 

These games should be supported on the new cores? What systems are they on? Have you tested them on the new cores that I released today?

if you want to continue having those menu options for now, you can set `EJS_oldCores` to true. Please note that the old cores, the emulatorjs.com cores (even the “new” ones on the website) use about 3-10 times as much cpu, making them much slower

(thanks for actually providing detail on what your issue was)

**Comment by shaylevary** [comment]
Hi,
These are mainly arcade games that run on different MAME cores.
When I try to load them using your script (latest version with the new cores), the game loads but ends up with a black screen.
However, when I try to load the original emulatorjs script files - the games work fine.

Example of games:

Killer Instinct
using core:
https://www.emulatorjs.com/cores/mame2003-wasm.data?v=3

Golden Axe Death Adder
using core:
https://www.emulatorjs.com/cores/mame-4-wasm.data?v=2

For the old menu options - Thanks, i will set EJS_oldCores to true for the snes games until fix/update will be released.

Thank you.

**Comment by ethanaobrien** [comment]
I’ll try to get mame compiled to the new cores when I can

I should also be able to get the menu settings thing done today

**Comment by ethanaobrien** [comment]
done!
