### ISSUE TITLE
Request consoles

### ISSUE THREAD

**Issue by Protektor-Desura** [emulatorjs/emulatorjs#315]
Do you think it would be possible to add:

These added would give you all [second generation consoles](https://en.wikipedia.org/wiki/Home_video_game_console_generations#Second_generation_(1976%E2%80%931992)).
------
Fairchild Channel F ([Libretro](https://docs.libretro.com/library/fbneo/))
Mattel Intellivision ([Libretro](https://docs.libretro.com/library/freeintv/))

These added would give you all [third generation consoles](https://en.wikipedia.org/wiki/Home_video_game_console_generations#Third_generation_(1983%E2%80%932003))
------
Atari XEGS ([MAME 0.246](https://emulation.gametechwiki.com/index.php/Atari_8-bit))

These added would give you all [fourth generation consoles](https://en.wikipedia.org/wiki/Home_video_game_console_generations#Fourth_generation_(1987%E2%80%932004))
------
Neo Geo (or does Neo Geo CD already support the cartridges too? or via MAME?)
Philips CD-i ([Libretro](https://www.libretro.com/index.php/category/philips-cd-i/))

These added would give you all [fifth generation consoles](https://en.wikipedia.org/wiki/Home_video_game_console_generations#Fifth_generation_(1993%E2%80%932006))
------
FM Towns Marty ([MAME?](http://nonmame.retrogames.com/))
Amiga CD32 ([MAME 0.246](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=cd32)) ([Libretro](https://docs.libretro.com/library/puae/))
NEC PC-FX ([Libretro](https://docs.libretro.com/library/beetle_pc_fx/))
Apple Pippin (no support in Retroarch?)

These added would give you all [sixth generation handhelds](https://en.wikipedia.org/wiki/Sixth_generation_of_video_game_consoles)
------
Nokia N-Gage (no support in Retroarch?) (https://github.com/EKA2L1/EKA2L1)
Neo Geo Pocket Color ([Libretro](https://docs.libretro.com/library/beetle_neopop/))

These added would give you all [seventh generation handhelds](https://en.wikipedia.org/wiki/Seventh_generation_of_video_game_consoles)
------
Sony PSP ([Libretro](https://docs.libretro.com/library/ppsspp/))

EXTRAS

I would love to see DOSBox supported.
https://github.com/dreamlayers/em-dosbox

I would love to see ScummVM supported.
https://github.com/juj/emscripten-scummvm
https://github.com/gr33k/emscripten-scummvm

**Comment by ethanaobrien** [comment]
I’ll look at this. I have dos planned I haven’t started on it yet because I know the inputs are going to be a little complicated. Most likely the consoles that need Vulcan (like psp) will not work, and I can only run retroarch supported consoles. I’ll look at them and see which I can do

**Comment by Protektor-Desura** [comment]
Well all of them should be supported because they are supported in Retroarch or MAME which is in Retroarch. Neo Geo should be supported in MAME, the non-CD version.

Even DOSBox & ScummVM are in Retroarch.

If you want to look at ExoDOS. They have everything pre-configured to just work with DOSBox. Plus I linked to a couple of DOSBox emscripten versions.

https://www.retro-exo.com/exodos.html

I posted some examples of ScummVM and emscripten from Retroarch. You may want to look at this as well.

https://www.retro-exo.com/scummvm.html

**Comment by Protektor-Desura** [comment]
I forgot to add Sega SG-1000 which is supported in other people's fork since it is a basic thing from Retroarch.

**Comment by ethanaobrien** [comment]
Here is what is and what is not possible (and if not, why)

Not Possible
- [FBNeo](https://github.com/libretro/FBNeo) - emscripten build target not supported
- Atari XEGS - I couldnt find a libretro repository for MAME 0.246
- [Neo Geo](https://github.com/libretro/neogeo_libretro) - emscripten build target not supported (and it uses cmake)
- Philips CD-i - I couldnt find a libretro repository for this core
- Apple Pippin - Nope, not in retroarch
- Nokia N-Gage - Also, nope, not in retroarch
- Neo Geo Pocket Color - I couldnt find a libretro repository for this core
- [PSP](https://github.com/libretro/ppsspp) - emscripten build target not supported (and it uses cmake)
- [ScummVM](https://github.com/libretro/scummvm) - emscripten build target not supported
- Sega SG-1000 - I couldnt find a libretro repository for this core

Please note: just because it can compile to emscripten does not mean I can support it, it must be mapped in emscripten.

Possibly possible
- [FreeIntv](https://github.com/libretro/FreeIntv)
- [Neo Geo CD](https://github.com/libretro/neocd_libretro)
- [PUAE](https://github.com/libretro/libretro-uae)
- [Beetle PC-FX](https://github.com/libretro/beetle-pcfx-libretro)
- [dosbox](https://github.com/libretro/dosbox-libretro)

**Comment by ethanaobrien** [comment]
Here is why each core is not possible

- [FBNeo](https://github.com/libretro/FBNeo) - emscripten build target not supported
- Atari XEGS - I couldnt find a libretro repository for MAME 0.246
- [Neo Geo](https://github.com/libretro/neogeo_libretro) - emscripten build target not supported (and it uses cmake)
- Philips CD-i - I couldnt find a libretro repository for this core
- Apple Pippin - Nope, not in retroarch
- Nokia N-Gage - Also, nope, not in retroarch
- Neo Geo Pocket Color - I couldnt find a libretro repository for this core
- [PSP](https://github.com/libretro/ppsspp) - emscripten build target not supported (and it uses cmake)
- [ScummVM](https://github.com/libretro/scummvm) - emscripten build target not supported
- Sega SG-1000 - I couldnt find a libretro repository for this core
- [Neo Geo CD](https://github.com/libretro/neocd_libretro) - emscripten build target not written correctly (broken)
- [PUAE](https://github.com/libretro/libretro-uae) - emscripten build target not written correctly (broken)
- [Beetle PC-FX](https://github.com/libretro/beetle-pcfx-libretro) - emscripten build target not written correctly (broken)
- [dosbox](https://github.com/libretro/dosbox-libretro) - emscripten build target not written correctly (broken)
- [FreeIntv](https://github.com/libretro/FreeIntv) - Not supported by the wrapper and requires modifications that would also require modifying other systems

Please note: just because it can compile to emscripten does not mean I can support it, it must be wrapped in retroarch.

**Comment by TRusselo** [comment]
<img width="1222" height="700" alt="Image" src="https://github.com/user-attachments/assets/06c8e406-4ca4-4d3f-8ad4-5d1cd1ccb4dd" />

teaser
