### ISSUE TITLE
Network feature was removed on latest version of script

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#326]
Hi,

I've noticed that you've removed the network feature on the latest version of this emulatorjs script, I've tried to enabled old cores settings, but it still didn't appear.
Why did you disabled it from the script? (i've noticed also emuserver github is down).

**Comment by ethanaobrien** [comment]
I removed netplay because the compatibility is very very small and there's bound to be more issues with compatibility and the new cores. There was also that cors issue that came up and I couldn't resolve so, for the moment, I stripped out the netplay engine.

I will probably add it in in the future, but this isn't guaranteed

**Comment by shaylevary** [comment]
Ok, Thank you. 
I think it should be disabled by default, but can be enabled by param, because it worked great for me on many arcade games.
BTW, Can i get the latest emuserver files that you've fixed few days ago?

**Comment by ethanaobrien** [comment]
Actually, the fix just made things worse.

Just keep using the ones you have and go back in this commit history to use netplay. I'm not supporting the feature at all for the moment

**Comment by shaylevary** [comment]
ok, thank you.

**Comment by jeffabner** [comment]
friend shaylevary, could you send me the version that works with netplay, my email jeffhardyabner@hotmail.com.
