### ISSUE TITLE
way netplay is stop working on new ver emulatorjs 

### ISSUE THREAD

**Issue by lyarinet** [emulatorjs/emulatorjs#329]
way netplay is stop working on new update emulatorjs

**Comment by shaylevary** [comment]
Hi,

I've asked the same question yesterday, and got replied that this feature have been disabled because it's not stable yet.
Look here: https://github.com/ethanaobrien/emulatorjs/issues/326#

Personally, I still think that this feature should be enabled via the script parameter (but by default disabled), because i used it alot on many arcades games, and it worked wonderful.

**Comment by lyarinet** [comment]
> Hi,
> 
> I've asked the same question yesterday, and got replied that this feature have been disabled because it's not stable yet. Look here: #326
> 
> Personally, I still think that this feature should be enabled via the script parameter (but by default disabled), because i used it alot on many arcades games, and it worked wonderful.

were to enable on script

**Comment by Ramaerel** [comment]
Your best bet is to go back a couple of versions to where Netplay was still enabled.
