### ISSUE TITLE
PSX game using PBP file

### ISSUE THREAD

**Issue by EmulatorOS** [emulatorjs/emulatorjs#402]
Some assets are missing after starting game. [Link](https://emulatoros.github.io/games/tekken3)
[emulatoros.github.io-1666663912825.log](https://github.com/EmulatorJS/EmulatorJS/files/9856601/emulatoros.github.io-1666663912825.log)

**Comment by ethanaobrien** [comment]
This is because of [beetle psx](https://github.com/libretro/beetle-psx-libretro). This is a known issue (see https://github.com/libretro/beetle-psx-libretro/issues/130, https://github.com/libretro/beetle-psx-libretro/issues/241). This would be something to open [here](https://github.com/libretro/beetle-psx-libretro/issues) since this is a retroarch issue
