### ISSUE TITLE
How do I contribute?

### ISSUE THREAD

**Issue by r1v1r** [emulatorjs/emulatorjs#485]
emu-main.js and emulator.js are mostly obfuscated. Is there a copy of the source that isnt obfuscated?

**Comment by ethanaobrien** [comment]
>Is there a copy of the source that isnt obfuscated?

No, those are the main copies of the files. The de-obfuscation has been taking place over time.

The only thing obfuscated at this point are the variable names

**Comment by r1v1r** [comment]
Does that mean this project is normally developed with obfuscated variable names? intentionally?

**Comment by ethanaobrien** [comment]
No, the project was initially obfuscated. If you look at the changelog and go back to let's say [the first commit](https://github.com/EmulatorJS/EmulatorJS/blob/be2db16cba8bd85bf901cd89ca6de51414cea792/data/emulator.js) it's been majorly de-obfuscated. This project was originally emulatorjs.com's code, but since there was absolutely no license or terms on their website I was able to take the code, make it more open, remove ads, improve the emulators (they're much faster now). This is why the file names are obfuscated.

**Comment by r1v1r** [comment]
Ahhh I see now. Thanks for the context.
