### ISSUE TITLE
where to post rom url

### ISSUE THREAD

**Issue by Rafa69420** [emulatorjs/emulatorjs#500]
im try to use to make website with roms or roms hack (if possible) but what is rom url can you help me?
ps im using code editor on website of emulatorjs

**Comment by wndalci** [comment]
I am not sure I understand what you are asking, and I am pretty new to this project, but I will answer to the best of my abilities.

Making a website which allows people to play roms or romhacks (roms hosted on site) is illegal, and can get you in serious trouble. This is due to you sharing intellectual property, among other things

Again, I am not at all an expert of this project, nor do I fully understand what you are asking, but I hope I can lean you in the correct direction.
