### ISSUE TITLE
How to put the video game at the center?

### ISSUE THREAD

**Issue by ildomandatore** [emulatorjs/emulatorjs#55]
On Wordpress, by default the elements are aligned to the left. How do I move the rectangle to the center?
[https://oldfreegame.com/en/nintendo/gameboy-advance/dragonball-z-buu-s-fury/](https://oldfreegame.com/en/nintendo/gameboy-advance/dragonball-z-buu-s-fury/)

**Comment by xxxnewbiexxx** [comment]
Hi, you need to align to the center using Wordpress editor or you can try something like this:

```
<div style="text-align:center;">
 
///emulator embed code goes here///
 
</div>
```

Hope it helps.

**Comment by ildomandatore** [comment]
I did some tests, but I wasn't able to get the desired result.

Would you show me all the code as a point of inspiration? It's fine even without the urls.

**Comment by xxxnewbiexxx** [comment]
Hi, the code would be something like this:

```
<div style="text-align:center;">
 
<div style="width:640px;height:480px;max-width:100%">
<div id="game"></div>
</div>
<script type="text/javascript">
    EJS_player = '#game';
    EJS_gameUrl = ''; // Url to Game rom
    EJS_core = 'snes';
    EJS_mouse = false; // SNES Mouse
    EJS_multitap = false; // SNES Multitap
    EJS_pathtodata = 'data/'; //path to all of the wasm and js files. MUST all be in the same directory!!
</script>
<script src="data/loader.js"></script>
 
</div>
```

**Comment by ildomandatore** [comment]
that's what I did, but it didn't work. Later I try to clear the cache and see if it changes.

**Comment by ildomandatore** [comment]
It did not work. Are we sure that I am moving the game to the center?

**Comment by ildomandatore** [comment]
I tried other solutions, but I couldn't. Can you help me?

**Comment by ethanaobrien** [comment]
you can try [this](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_center_css) or [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center)

**Comment by allancoding** [comment]
Based on our findings, we cannot verify that you got a copy of emulatorjs from its official source. The cause of this is because of undocumented changes (meaning, there is no documentation on your site stating changes, which is required by license) or changes that have removed a link to source of the software. Stating the changes and linking to the original source is REQUIRED by license and we will refuse to service those who do not follow the license whether it be a requested feature, a possible bug, or a need for information. We have the right by law to refuse to service you. To dismiss this notice and be able to receive help, then add the stated changes to your website, and make sure a link to this page (or the information on the page itself) is clearly visible, and that there is a clear link to the source of the original GitHub project. If you get this message and make the required changes and break the license in this way again, then you will be prevented from opening any issues in the emulatorjs repository. No help will be given to make these changes (you managed to make the changes that break the license, you can fix it). We apologize for any inconvenience.
