### ISSUE TITLE
Game not starting

### ISSUE THREAD

**Issue by terminalgt** [emulatorjs/emulatorjs#556]
Im trying to make a gran turismo emulator and it sends me to retroarch homepage. im using a .cue file any reason why this isnt working? i have the usa version of the bios and game.
![Screenshot 2023-06-25 3 54 07 PM](https://github.com/EmulatorJS/EmulatorJS/assets/122653158/2af97934-0390-41cd-bf03-2f04d2911a3d)

**Comment by Hassen-The-Genius** [comment]
I have that same problem with beetle psx and beetle psx hw cores and i guess it may be a bug in these cores that what i got so far after some searching and i think the only way of playing any psx game right know may be using the old psx core, at least until they make a fix for this. I did that at the moment because i found no other solution, and i hope to find a fix, and thank you.

**Comment by terminalgt** [comment]
ill try this

**Comment by ethanaobrien** [comment]
Will be fixed in the next update

**Comment by ethanaobrien** [comment]
Fixed. This issue is actually a user error
