### ISSUE TITLE
Adding custom emulators?

### ISSUE THREAD

**Issue by teddblue** [emulatorjs/emulatorjs#67]
Is there any way I could add other emulators' source code?

**Comment by allancoding** [comment]
What would that accomplish? What would you like to do that is not there?

**Comment by teddblue** [comment]
Some other emulators have other capabilities, melon ds can link locally via wifi, bgb can do something similar. Sorry for the belated response

**Comment by ethanaobrien** [comment]
Wifi on the ds will not be possible without running all data through a proxy due to the webassembly permissions

You could set `EJS_CUSTOM_COREFILE` to the name of a custom core file and place it in the data directory

Note: to package the emulator, you need set the out file name to `retroarch.js` and `retroarch.wasm`. You can then 7z the files together (directly, not in a folder) and then use the tool below to encrypt it
[decrypt.zip](https://github.com/ethanaobrien/emulatorjs/files/7824527/decrypt.zip)

**Comment by ethanaobrien** [comment]
assuming issue resolved - I have provided info necessary to use different core files
