### ISSUE TITLE
Star Fox 64

### ISSUE THREAD

**Issue by JScripto** [emulatorjs/emulatorjs#722]
The game crashes on **mupen64plus_next**

The save state does not load on **parallel_n64** (Loud Static Sound)

**Comment by ethanaobrien** [comment]
Logs?

>The save state does not load on parallel_n64 (Loud Static Sound)

Saves are not often cross core

**Comment by thelamer** [comment]
I have been testing this locally, it seems to be related to running out of memory. Even then there are many graphical clitches due to GLES3 implementation and lack of the RDRAM copy support. Unless you are willing to bump up to giving it a gig in a single tab I don't think this is fixable in the current implementation of mupen64 in webassembly. This might just be part of the compatibility stuff that wont happen until emscripten supports more opengl stuff.
