### ISSUE TITLE
[Bug] Issue With Code Editor

### ISSUE THREAD

**Issue by Earth231** [emulatorjs/emulatorjs#748]
I use the code editor to play old games from the Game Boy Advance, DS, N64, and Sega Genesis (or Mega Drive, same thing). Normally, when using any computer on any OS, it loads up as normal. However, whenever I have tried to load up a game, it just shows a black screen. I thought it might be a one-time error, but I have tried those different systems, with different games, with every option. I have tried to add the BIOS files, unzip the game ROMs, etc. But nothing has worked. The weird thing is, these files were downloaded almost four months ago and have worked perfectly up until now. I think it might be some kind of bug, and I want to know if there is anything I can do to fix it.

Here is a screen capture of me trying to load up Pokémon Emerald for the GBA:

https://github.com/EmulatorJS/EmulatorJS/assets/148776234/9e085b81-65a1-4746-ba89-996c68abdc75

**Comment by MorenoIgor** [comment]
Was going to report a similar thing for the Master System core. It only started working again when I set it to debug mode:
`EJS_DEBUG_XX = true;`

**Comment by ethanaobrien** [comment]
@MorenoIgor can I get a log of the console without debug enabled

**Comment by Earth231** [comment]
How do you do that? This is just the html file, nothing else, so how do you get the console log? Please list the steps to do this.

**Comment by ethanaobrien** [comment]
```
To collect a log of the console.
1. Add the following line to your code
EJS_DEBUG_XX = true;
2. Right click and click `inspect`.
3. Select the `console` tab at the top.
4. then reload the broken page.
5. Right click on the console and click `Save as...`
```

**Comment by MorenoIgor** [comment]
@ethanaobrien Sorry for the delay. First, this is the error reported when running it not on debug mode:

`emulator.js:1225 Uncaught (in promise) ReferenceError: GamepadHandler is not defined
    at EmulatorJS.bindListeners (emulator.js:1225:28)
    at new EmulatorJS (emulator.js:284:14)
    at loader.js:127:27`

And this is the full log on debug mode:

`emulator.js:1952 {playPause: false, restart: true, mute: false, settings: false, fullscreen: true, …}
emulator.js:1088 (2) ['-v', '/vania.sms']
emulator.js:1062 Built for EmulatorJS Version 4.0.6
emulator.js:1062 Download a copy from https://github.com/EmulatorJS/EmulatorJS
emulator.js:1062 View the licence here: https://github.com/EmulatorJS/EmulatorJS/blob/main/LICENSE
emulator.js:1067 [INFO] RetroArch 1.16.0 (Git a6bd6ff8a6)
emulator.js:1067 [INFO] === Build =======================================
emulator.js:1067 [INFO] Capabilities: 
emulator.js:1067 [INFO] Version: 1.16.0
emulator.js:1067 [INFO] Git: a6bd6ff8a6
emulator.js:1067 [INFO] Built: Oct  2 2023
emulator.js:1067 [INFO] =================================================
emulator.js:1067 [INFO] [Input]: Found input driver: "emulatorjs".
emulator.js:1067 [INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
emulator.js:1067 [INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
emulator.js:1067 [INFO] [Environ]: SET_CONTROLLER_INFO.
emulator.js:1067 [INFO] [Environ]: SET_INPUT_DESCRIPTORS:
emulator.js:1067 [INFO] [Environ]: RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE.
emulator.js:1067 [INFO] [Content Override]: File Extension: 'mdx' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1067 [INFO] [Content Override]: File Extension: ' md' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1067 [INFO] [Content Override]: File Extension: 'bin' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1067 [INFO] [Content Override]: File Extension: 'smd' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1067 [INFO] [Content Override]: File Extension: 'gen' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1067 [INFO] [Content Override]: File Extension: 'bms' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1067 [INFO] [Content Override]: File Extension: 'sms' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1067 [INFO] [Content Override]: File Extension: ' gg' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1067 [INFO] [Content Override]: File Extension: ' sg' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1067 [INFO] [Content Override]: File Extension: '68k' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1067 [INFO] [Content Override]: File Extension: 'sgd' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1067 [INFO] [Environ]: GET_VFS_INTERFACE. Core requested version >= V2, providing V3.
emulator.js:1067 [INFO] [Environ]: GET_LED_INTERFACE.
emulator.js:1067 [INFO] [Overrides]: Redirecting save file to "/data/saves/Genesis Plus GX/vania.srm".
emulator.js:1067 [INFO] [Overrides]: Redirecting save state to "/home/web_user/retroarch/userdata/states/Genesis Plus GX/vania.state".
emulator.js:1067 [INFO] [Environ]: PERFORMANCE_LEVEL: 1.
emulator.js:1067 [INFO] [Environ]: GET_LOG_INTERFACE.
emulator.js:1067 [INFO] [Environ]: PERFORMANCE_LEVEL: 7.
emulator.js:1067 [INFO] [Environ]: SET_SERIALIZATION_QUIRKS.
emulator.js:1067 [INFO] [Environ]: SET_DISK_CONTROL_INTERFACE.
emulator.js:1067 [INFO] [Content]: Loading content file: "/vania.sms".
emulator.js:1067 [INFO] [Environ]: RETRO_ENVIRONMENT_GET_GAME_INFO_EXT.
emulator.js:1067 [INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
emulator.js:1067 [libretro INFO] Frontend supports RGB565 - will use that instead of XRGB1555.
emulator.js:1067 [WARN] [Environ]: SYSTEM DIR is empty, assume CONTENT DIR /vania.sms
emulator.js:1067 [INFO] [Environ]: SYSTEM_DIRECTORY: "".
emulator.js:1067 [INFO] [Environ]: GET_SAVE_DIRECTORY.
emulator.js:1067 [INFO] [Environ]: SET_AUDIO_BUFFER_STATUS_CALLBACK.
emulator.js:1067 [INFO] [Replay]: Found last replay slot: #0
emulator.js:1067 [INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
emulator.js:1067 [INFO] [Core]: Geometry: 256x192, Aspect: 1.524, FPS: 59.92, Sample rate: 44100.00 Hz.
emulator.js:1067 [INFO] [Audio]: Set audio input rate to: 44156.86 Hz.
emulator.js:1067 [INFO] [Video]: Set video size to: 879x576.
emulator.js:1067 [INFO] [EGL] Falling back to eglGetDisplay
emulator.js:1067 [INFO] [EGL]: EGL version: 1.4
emulator.js:1067 [INFO] [EGL]: Current context: 0xf234.
emulator.js:1067 [INFO] [EMSCRIPTEN/EGL]: Dimensions: 300x150
emulator.js:1067 [INFO] [GL]: Found GL context: "egl_emscripten".
emulator.js:1067 [INFO] [GL]: Detecting screen resolution: 300x150.
emulator.js:1067 [INFO] [GL]: Vendor: WebKit, Renderer: WebKit WebGL.
emulator.js:1067 [INFO] [GL]: Version: OpenGL ES 2.0 (WebGL 1.0 (OpenGL ES 2.0 Chromium)).
emulator.js:1067 [WARN] [GL]: GLES implementation does not have BGRA8888 extension.
emulator.js:1067 [GL]: 32-bit path will require conversion.
emulator.js:1067 [INFO] [GL]: Using resolution 300x150.
emulator.js:1067 [INFO] [GL]: Default shader backend found: glsl.
emulator.js:1067 [INFO] [Shader driver]: Using GLSL shader backend.
emulator.js:1067 [WARN] [GL]: Stock GLSL shaders will be used.
emulator.js:1067 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1067 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1067 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1067 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1067 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1067 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1067 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1067 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1067 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1067 [INFO] [GL]: Using 4 textures.
emulator.js:1067 [INFO] [GL]: Loaded 1 program(s).
emulator.js:1067 [INFO] [Video]: Found display server: "null".
12The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. <URL>
emulator.js:1067 [INFO] [OpenAL]: Using 11 buffers of 1024 bytes.
emulator.js:1067 [INFO] [Audio]: Started synchronous audio driver.
emulator.js:1067 [INFO] [Display]: Found display driver: "gl".
emulator.js:1067 [INFO] [Config]: Saved new config to "/home/web_user/retroarch/userdata/retroarch.cfg".
emulator.js:1067 [INFO] [Playlist]: Loading history file: "/home/web_user/retroarch/userdata/content_history.lpl".
emulator.js:1067 [INFO] [Playlist]: Loading history file: "/home/web_user/retroarch/userdata/content_music_history.lpl".
emulator.js:1067 [INFO] [Playlist]: Loading favorites file: "/home/web_user/retroarch/userdata/content_favorites.lpl".
emulator.js:1067 [ERROR] Cannot push NULL or empty core path into the playlist.
emulator.js:3752 shader disabled
emulator.js:1067 [ERROR] [GL]: none shader not supported, falling back to stock GLSL
emulator.js:1067 [INFO] [Shader driver]: Using GLSL shader backend.
emulator.js:1067 [WARN] [GL]: Stock GLSL shaders will be used.
emulator.js:1067 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1067 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1067 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1067 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1067 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1067 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1067 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1067 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1067 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1067 [INFO] [Shaders]: Applying shader: "".
emulator.js:3752 fps hide
emulator.js:3752 ff-ratio 3.0
emulator.js:1062 invalid core option ff-ratio. This is not an error.
emulator.js:3752 sm-ratio 3.0
emulator.js:1062 invalid core option sm-ratio. This is not an error.
emulator.js:3752 fastForward disabled
emulator.js:1062 invalid core option fastForward. This is not an error.
emulator.js:3752 slowMotion disabled
emulator.js:1062 invalid core option slowMotion. This is not an error.
emulator.js:3752 rewindEnabled disabled
emulator.js:1062 invalid core option rewindEnabled. This is not an error.
emulator.js:3752 rewind-granularity 6
emulator.js:1062 invalid core option rewind-granularity. This is not an error.
emulator.js:3752 save-state-slot 1
emulator.js:1062 invalid core option save-state-slot. This is not an error.
emulator.js:3752 save-state-location download
emulator.js:1062 invalid core option save-state-location. This is not an error.
emulator.js:3752 genesis_plus_gx_frameskip_threshold 33
emulator.js:3752 genesis_plus_gx_lowpass_range 60
emulator.js:3752 genesis_plus_gx_psg_preamp 150
emulator.js:3752 genesis_plus_gx_fm_preamp 100
emulator.js:3752 genesis_plus_gx_cdda_volume 100
emulator.js:3752 genesis_plus_gx_pcm_volume 100
emulator.js:3752 genesis_plus_gx_audio_eq_low 100
emulator.js:3752 genesis_plus_gx_audio_eq_mid 100
emulator.js:3752 genesis_plus_gx_audio_eq_high 100
emulator.js:3752 genesis_plus_gx_enhanced_vscroll_limit 8
emulator.js:3752 genesis_plus_gx_psg_channel_0_volume 100
emulator.js:3752 genesis_plus_gx_psg_channel_1_volume 100
emulator.js:3752 genesis_plus_gx_psg_channel_2_volume 100
emulator.js:3752 genesis_plus_gx_psg_channel_3_volume 100
emulator.js:3752 genesis_plus_gx_md_channel_0_volume 100
emulator.js:3752 genesis_plus_gx_md_channel_1_volume 100
emulator.js:3752 genesis_plus_gx_md_channel_2_volume 100
emulator.js:3752 genesis_plus_gx_md_channel_3_volume 100
emulator.js:3752 genesis_plus_gx_md_channel_4_volume 100
emulator.js:3752 genesis_plus_gx_md_channel_5_volume 100
emulator.js:3752 genesis_plus_gx_sms_fm_channel_0_volume 100
emulator.js:3752 genesis_plus_gx_sms_fm_channel_1_volume 100
emulator.js:3752 genesis_plus_gx_sms_fm_channel_2_volume 100
emulator.js:3752 genesis_plus_gx_sms_fm_channel_3_volume 100
emulator.js:3752 genesis_plus_gx_sms_fm_channel_4_volume 100
emulator.js:3752 genesis_plus_gx_sms_fm_channel_5_volume 100
emulator.js:3752 genesis_plus_gx_sms_fm_channel_6_volume 100
emulator.js:3752 genesis_plus_gx_sms_fm_channel_7_volume 100
emulator.js:3752 genesis_plus_gx_sms_fm_channel_8_volume 100
emulator.js:4065 Available core options {shader: {…}, fps: {…}, ff-ratio: {…}, sm-ratio: {…}, fastForward: {…}, …}
emulator.js:1067 [INFO] [Environ]: RETRO_ENVIRONMENT_SET_MINIMUM_AUDIO_LATENCY.`

**Comment by ethanaobrien** [comment]
Oh I think I know why this happens, I'll get this changed

**Comment by Earth231** [comment]
Thank you so much

**Comment by ethanaobrien** [comment]
Fix just pushed. Might take a second for the website to update. Be sure to clear your cache.
