### ISSUE TITLE
Mobile devices getting hot after 5 minutes of play

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#76]
I have noticed thermal issues on mobile devices after 5 minutes of play.

Is this normal?
Native mobile emulator apps do not have this issue.

**Comment by ethanaobrien** [comment]
@imneckro 
This may happen on some devices. Not just mobile.

This is normal. The device may get hot because an emulator has to basically pretend that is the actual system, which uses lots of cpu.

>Native mobile emulator apps do not have this issue.

This project is a webassembly / javascript emulator. The webassembly technology is not as fast as a native app, which causes it to use more cpu.

I am going to make an FRQ section when I get the time. I am going to add this.
