### ISSUE TITLE
[Bug] errors download 100%

### ISSUE THREAD

**Issue by Codigohispano** [emulatorjs/emulatorjs#805]
I have come here as a client. since practically everyone uses this emulation system. and as a client I cannot start some video game platforms. I can't start even saturn. nor psx. nor n64. nor DS. It says that it downloads the core or the data at 100%. In most cases the core, but it remains frozen and does not exceed 100%. appears in the credits of those websites emulatorjs 0.5.27. not 4.0.11. If I knew the emails of the website owners I would ask them to update the version. Any way as a client I could make PSX or N64 work? I know I write it here but there is no other section.

**Comment by ethanaobrien** [comment]
>appears in the credits of those websites emulatorjs 0.5.27. not 4.0.11

Thats because those website probably use the https://emulatorjs.com emulator, and not this one which is faster and has a wider range of device support

>If I knew the emails of the website owners I would ask them to update the version.

Yes, look for a "contact me" on their website, and link this github issue, and include a description of your issues

>Any way as a client I could make PSX or N64 work?

You'd need to contact the site owners and convince them to switch to this, open source, version of emulatorjs

**Comment by asteng88** [comment]
Same here. I have one set of ROMS for NES and they work perfectly. When I try to run MAME roms, it stops at "Loading Bios: 100%" and freezes. I know these roms work as I tested them with MAME 32 Version 0.34 (1998) version.
I am running it on Docker on my Synology NAS.

**Comment by ethanaobrien** [comment]
>I am running it on Docker on my Synology NAS

This sounds like its linuxservers docker, which is a completely separate project


I'm closing this issue since its unrelated to this project (OP posted about emulatorjs.com)
