### ISSUE TITLE
Did you add the game speed control setting to EmulatorJS? and if so Where did you put it?

### ISSUE THREAD

**Issue by deadman616** [emulatorjs/emulatorjs#817]
I'm playing a game but I can't find the game speed control settings anywhere to slow down the game. Did you add the game speed control sitting to EmulatorJS? and if so Where did you put it? make it easy to find.

**Comment by ethanaobrien** [comment]
You need to enable it in the settings menu for the settings (bottom right) for it to appear in the controller settings menu. This is done because if enabled by default, there is a noticeable performance difference on lower end devices


My bad - only rewind slows down performance

The controls for slowing down the game are in the settings menu and the control mapping menu
