### ISSUE TITLE
The browser outputs an error.

### ISSUE THREAD

**Issue by ZhaoTonggang** [emulatorjs/emulatorjs#853]
The demo web page has an error in the browser, and the screen is black, and the browser debug output is shown in the figure.
![mmexport1720473627932](https://github.com/EmulatorJS/EmulatorJS/assets/81669862/9e733088-ffe8-4919-bbac-2679f7ab1d6a)

**Comment by ethanaobrien** [comment]
That is not the plain demo site (proxy?), or code is injected onto the page which is causing the emulator to fail.

While I do not support usage of the demo through these methods, this may be fixable. I will need the proper log though: please enable `EJS_DEBUG_XX` in the console **before** selecting any sort of rom.

I am closing this issue, since it is extremely unlikely to be an issue with the demo page itself.
You can still reply with the requested information to this issue and we’ll see if it’s something that needs to be fixed

**Comment by ZhaoTonggang** [comment]
> That is not the plain demo site (proxy?), or code is injected onto the page which is causing the emulator to fail.
> 
> While I do not support usage of the demo through these methods, this may be fixable. I will need the proper log though: please enable `EJS_DEBUG_XX` in the console **before** selecting any sort of rom.
> 
> I am closing this issue, since it is extremely unlikely to be an issue with the demo page itself. You can still reply with the requested information to this issue and we’ll see if it’s something that needs to be fixed

I tried to fix it.
#855 Fixed the error of the "foreach" function in the browser.
