### ISSUE TITLE
[Request] Possible Lower-Intensity Setting For Lower End Devices?

### ISSUE THREAD

**Issue by Earth231** [emulatorjs/emulatorjs#905]
[PokÃ©mon Platinum-9-2-2024.webm](https://github.com/user-attachments/assets/e14bc9e8-b9df-4b14-bb47-c43a8e1a6beb)

First off, I want to acknowledge the fact that most everything runs great on the emulator, on any device. However, PS, N64, DS, Sega Saturn, and Atari Jaguar games can have a lot of slowdown on Chromebooks and other low-end devices; for instance, playing Pokemon Platinum (for the DS) with shaders turned off and no extra effects added, runs at about 1/3 speed. Again, the game runs great on better hardware, but I just wondered if there was some kind of setting that could be implemented into the emulator to allow us Chromebook and old PC users to have a better playing experience.

**Comment by Earth231** [comment]
Maybe an option to render and process only half of the frames or something?

**Comment by ethanaobrien** [comment]
> However, PS, N64, DS, Sega Saturn, and Atari Jaguar games can have a lot of slowdown on Chromebooks and other low-end devices

(Just a fact check) no need to specify chromebooks, just "lower end devices" is fine, since *most* chromebook models are really good quality. The ones you'll actually see out in schools though are the super cheap bad ones yeah.

> Maybe an option to render and process only half of the frames or something?

That isn't *quite* how it works, since frame speed and emulation speed are tied together.

There is no fix to this issue, since (especially when we have no JIT) the host devices need to be significantly more powerful than the console being emulated. In this case it's most definitely a CPU bottleneck.

You can try the following (for nds):
- Try using the Desmume core, this must be configured in the html code (at the moment, a toggle through the settings menu is eventually coming). This core often runs better on lower end devices.  - I'd want to switch desmume back to default, though I do not want to break compatibility with save states. Its up to site owners to set this at the moment.
- The desmume core has a "frameskip" option, similar to what you mentioned. This should significantly help performance.

For all other consoles, there's not much that can be done.
For n64 you can always give parallel-n64 a try, which never hurts.
For playstation and n64, another issue is likely memory size. Overflowing into swap/zram can be slow.

**Comment by Earth231** [comment]
I checked out a site that I knew had Desmume, and while it doesn't have fullscreen and all of the other extra options of melonDS, it does run at a solid 60 fps. Thank you so much!

**Comment by ethanaobrien** [comment]
I do find it interesting how some websites disable the full screen button

Closing issue as completed
