### ISSUE TITLE
[Bug] Audio static in FireFox

### ISSUE THREAD

**Issue by programmingPug** [emulatorjs/emulatorjs#915]
Issue is present on https://demo.emulatorjs.org/

Video: https://youtube.com/shorts/hE6rHbMruGM?feature=share
FireFox: 132.0.2 (Latest)
Load any game and listen.

**Comment by ethanaobrien** [comment]
What hardware is this on?
Does this happen in chromium based browsers?
What core/system are you using?
Does this occur with an NES game?

**Comment by ethanaobrien** [comment]
Closing - not enough information to diagnose

**Comment by dattas** [comment]
I can confirm this issue on Firefox 133.0 on Nixos 24.11. I tested this on https://demo.emulatorjs.org/ (Stable 4.1.1 and nightly)
I'm using a AMD Ryzen 7 5800X, 32gb of ram with a nvidia GTX 1070.
I'm using the snes core. I tried with the nes core and has the same problem.
Chromium does not exhibit the issue with the same hardware.

**Comment by ethanaobrien** [comment]
@dattas this either isn't the same issue, or its not an issue at all.

Firefox (due to how it does sandboxing) is fundamentally slower (and has more security issues because of the way it does sandboxing, though that's besides the point). Seeing how the issue is Firefox specific tells me its an issue with the Firefox webassembly runtime speed, not with EmulatorJS
