### ISSUE TITLE
Firefox is noticeably slower than Chromium based browsers

### ISSUE THREAD

**Issue by RealMalachi** [emulatorjs/emulatorjs#928]
Audio seems to degrade on Firefox. It works fine on other browsers I've tested (all of which being Chromium-based fwiw)
Firefox version: v133.0.3, though the same issue was seemingly reported for v132.0.2 a month ago #915
 -Installed extensions: uBlock Origin (sorry), Google Translate, Dark Reader
Emu-JS version: v4.2, though I first found out about this due to a somewhat scummy website using v4.0.1.2
Hardware: a gaming laptop running windows 10, was far from being maxed out

Here's [footage of Somari](https://youtu.be/dydY7e2pMcY) demonstrating the problem. Basically, the audio output initially starts out fine, but roughly 5 seconds in it'll slowly degrade into an irritating noise, with most mega drive games especially sounding horrible because of that. The type and severity can change sometimes when selecting UI options, minimizing the window, or leaving the tab inactive for a short while. Oddly, vsync doesn't seem to effect this issue.
SNES and MD also have some weirdness going off of the UIs built-in frame timer, sometimes it's at a proper frame rate, sometimes it says it's around 20 but the actual game is updating at rates that implies it's at 60, sometimes it caps at weird frame rates around 45 with the emulation speed reflecting that, it's a bloody wild west of inconsistency.

**Comment by ethanaobrien** [comment]
This is a known "issue" that EmulatorJS can't possibly fix, and isn't an issue with this project.

The Firefox WebAssembly runtime is, point blank, slow compared to chromium (Firefox as a whole is slower, because of how bloated the codebase is). You mentioned that Chromium browsers all work fine, and this is because they have a different WebAssembly runtime engine. Even my gaming PC (14700k 4070TIS) cannot get pure 60fps with no crackling in Firefox.

> sometimes it says it's around 20 but the actual game is updating at rates that implies it's at 60

If vsync is off, the frame rate is the emulation speed, 60fps being 100% speed. If it is on, it uses the browsers `requestAnimationFrame` method which will reflect your refresh rate (while being locked to a slower speed if your monitor is lower than 60Hz). This is because of how RetroArch handles internal timing.

Sadly, this isn't an issue I can fix nor an issue with this project. I'll be closing this issue, though will also be changing the title and pinning it, since many people have come here wondering about it.
